spring:
  application:
    name: INVOICES-MICROSERVICE
  # ================================
  # Datasource Config
  # ================================
  datasource:
    url: jdbc:h2:mem:mydb
    username: moustafa
    password: moustafa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update